mode:
  type: train
#  agent_policies: ../Domains/Medium_60_AGVs/Results/neural_nets.csv # file containing agent policies
#  eval_file: ../Domains/Medium_60_AGVs/Results/evaluation_9.csv # file containing best teams
domain:
  folder: ../Domains/Medium_60_AGVs_link/
graph:
  vertices: vertices.csv
  edges: edges.csv
  capacities: capacities.csv
neuroevo:
  learn: true
  population_size: 10
  epochs: 200 # set to 1 in test mode
  runs: 10
simulation:
  steps: 200
  agvs: origins.csv
  goals: goals.csv
  agents: link
results:
  folder: Results/
  evaluation: evaluation
  policies: neural_nets.csv
