domain:
  folder: ../Domains/Medium_120_AGVs_link/
graph:
  vertices: vertices.csv
  edges: edges.csv
  capacities: capacities.csv
neuroevo:
  learn: true
  population_size: 10
  epochs: 200
  runs: 10
simulation:
  steps: 200
  agvs: origins.csv
  goals: goals.csv
  agents: link
results:
  folder: Results/
  evaluation: evaluation
  policies: neural_nets.csv
